const quizQuestions = [
    {
        question: "Which of these animals has black,gray,or brown stripes?",
        a: "Lion",
        b: "Tiger",
        c: "Monkey",
        d: "Panther",
        correct: "b",
    },
    {
        question: "Which of these animals has a shell called a carpace?",
        a: "Spider",
        b: "Snail",
        c: "Turtle",
        d: "Lizard",
        correct: "c",
    },
    {
        question: "Which of these marine animals has black,gray,or brown stripes?",
        a: "Lion",
        b: "Tiger",
        c: "Monkey",
        d: "Panther",
        correct: "b",
    },
    {
        question: "Which of these animals has black,gray,or brown stripes?",
        a: "Lion",
        b: "Tiger",
        c: "Monkey",
        d: "Panther",
        correct: "b",
    },
    {
        question: "Which of these animals has black,gray,or brown stripes?",
        a: "Lion",
        b: "Tiger",
        c: "Monkey",
        d: "Panther",
        correct: "b",
    },
    {
        question: "Which of these animals has black,gray,or brown stripes?",
        a: "Lion",
        b: "Tiger",
        c: "Monkey",
        d: "Panther",
        correct: "b",
    },
    {
        question: "Which of these animals has black,gray,or brown stripes?",
        a: "Lion",
        b: "Tiger",
        c: "Monkey",
        d: "Panther",
        correct: "b",
    },
    {
        question: "Which of these animals has black,gray,or brown stripes?",
        a: "Lion",
        b: "Tiger",
        c: "Monkey",
        d: "Panther",
        correct: "b",
    },
    {
        question: "Which of these animals has black,gray,or brown stripes?",
        a: "Lion",
        b: "Tiger",
        c: "Monkey",
        d: "Panther",
        correct: "b",
    },
    {
        question: "Which of these animals has black,gray,or brown stripes?",
        a: "Lion",
        b: "Tiger",
        c: "Monkey",
        d: "Panther",
        correct: "b",
    },
]