const quizQuestions = [
    {
        question: "Which of these animals has black,gray,or brown stripes?",
        a: "Lion",
        b: "Tiger",
        c: "Monkey",
        d: "Panther",
        correct: "b",
    },
    {
        question: "Which of these animals has black,gray,or brown stripes?",
        a: "Lion",
        b: "Tiger",
        c: "Monkey",
        d: "Panther",
        correct: "b",
    },
    {
        question: "Which of these animals has black,gray,or brown stripes?",
        a: "Lion",
        b: "Tiger",
        c: "Monkey",
        d: "Panther",
        correct: "b",
    },
    {
        question: "Which of these animals has black,gray,or brown stripes?",
        a: "Lion",
        b: "Tiger",
        c: "Monkey",
        d: "Panther",
        correct: "b",
    },
    {
        question: "Which of these animals has black,gray,or brown stripes?",
        a: "Lion",
        b: "Tiger",
        c: "Monkey",
        d: "Panther",
        correct: "b",
    },
    {
        question: "Which of these animals has black,gray,or brown stripes?",
        a: "Lion",
        b: "Tiger",
        c: "Monkey",
        d: "Panther",
        correct: "b",
    },
    {
        question: "Which of these animals has black,gray,or brown stripes?",
        a: "Lion",
        b: "Tiger",
        c: "Monkey",
        d: "Panther",
        correct: "b",
    },
    {
        question: "Which of these animals has black,gray,or brown stripes?",
        a: "Lion",
        b: "Tiger",
        c: "Monkey",
        d: "Panther",
        correct: "b",
    },
    {
        question: "Which of these animals has black,gray,or brown stripes?",
        a: "Lion",
        b: "Tiger",
        c: "Monkey",
        d: "Panther",
        correct: "b",
    },
    {
        question: "Which of these animals has black,gray,or brown stripes?",
        a: "Lion",
        b: "Tiger",
        c: "Monkey",
        d: "Panther",
        correct: "b",
    },
]